// AUTO-GENERATED by scripts/bundle-injected.js — do not edit manually
// Source: src/core/*.ts
function domDistiller(options?: any): any {
interface Rect {
  top: number;
  left: number;
  bottom: number;
  right: number;
  width: number;
  height: number;
}

interface DistilledNode {
  role: string;
  tag: string;
  text: string;
  locator: string;
  locatorFallback: string[];
  interactable: boolean;
  visible: boolean;
  editable: boolean;
  checked?: boolean;
  disabled?: boolean;
  attributes: Record<string, string>;
  rect: Rect;
  children: DistilledNode[];
}

interface DistillOptions {
  maxTextLength?: number;
  includeHidden?: boolean;
  checkObscured?: boolean;
}

/** Query for finding controls in the AST */
interface ControlQuery {
  text?: string;
  role?: string;
  tag?: string;
  locator?: string;
}

/** Options for astToMarkdown */
interface MarkdownOptions {
  columns?: string[];
  maxRows?: number;
}


function getRect(el: Element): Rect {
  const r = el.getBoundingClientRect();
  return {
    top: Math.round(r.top * 100) / 100,
    left: Math.round(r.left * 100) / 100,
    bottom: Math.round(r.bottom * 100) / 100,
    right: Math.round(r.right * 100) / 100,
    width: Math.round(r.width * 100) / 100,
    height: Math.round(r.height * 100) / 100,
  };
}

function isVisible(el: Element, opts: DistillOptions = {}): boolean {
  const cs = window.getComputedStyle(el);
  const rect = el.getBoundingClientRect();

  if (cs.display === 'none') return false;
  if (cs.visibility === 'hidden') return false;
  if (parseFloat(cs.opacity) < 0.01) return false;
  if (rect.width <= 0 || rect.height <= 0) return false;
  if (el.getAttribute('aria-hidden') === 'true') return false;

  if (opts.checkObscured) {
    const cx = rect.left + rect.width / 2;
    const cy = rect.top + rect.height / 2;
    if (cx < 0 || cy < 0 || cx > window.innerWidth || cy > window.innerHeight) {
      return false;
    }
    const topEl = document.elementFromPoint(cx, cy);
    if (!topEl) return false;
    if (topEl !== el && !el.contains(topEl) && !topEl.contains(el)) {
      return false;
    }
  }

  return true;
}


const INTERACTIVE_TAGS = new Set([
  'button', 'a', 'input', 'select', 'textarea', 'option', 'label',
  'summary', 'details', 'img', 'video', 'audio', 'canvas', 'iframe',
]);

const INTERACTIVE_ROLES = new Set([
  'button', 'link', 'menuitem', 'tab', 'checkbox', 'radio', 'switch',
  'slider', 'spinbutton', 'textbox', 'combobox', 'listbox', 'option',
  'treeitem', 'gridcell', 'columnheader', 'rowheader', 'row', 'cell',
  'searchbox', 'menuitemcheckbox', 'menuitemradio', 'progressbar',
]);

const STABLE_ATTRS = [
  'data-testid', 'data-test', 'data-qa', 'data-id',
  'id', 'name', 'aria-label', 'placeholder', 'title', 'alt', 'href', 'type', 'value',
];

function isInteractive(el: Element): boolean {
  const tag = el.tagName.toLowerCase();
  if (INTERACTIVE_TAGS.has(tag)) return true;

  const role = (el.getAttribute('role') || '').toLowerCase();
  if (INTERACTIVE_ROLES.has(role)) return true;

  if (el.getAttribute('contenteditable') === 'true') return true;
  if (el.hasAttribute('onclick')) return true;
  if ((el as HTMLElement).onclick != null) return true;

  const cursor = window.getComputedStyle(el).cursor;
  if (cursor === 'pointer' && (el as HTMLElement).tabIndex >= 0) return true;

  if (el.tagName.includes('-')) return true; // custom elements

  return false;
}

function normalizeText(text: string, maxLen = 200): string {
  return text.replace(/\s+/g, ' ').trim().slice(0, maxLen);
}

function getLabelText(el: Element): string {
  if (el.id) {
    const lbl = document.querySelector(`label[for="${CSS.escape(el.id)}"]`);
    if (lbl) return normalizeText((lbl as HTMLElement).innerText || lbl.textContent || '');
  }

  const parent = el.closest('label');
  if (parent) {
    const clone = parent.cloneNode(true) as HTMLElement;
    clone.querySelectorAll('input,select,textarea').forEach((c) => c.remove());
    return normalizeText(clone.innerText || clone.textContent || '');
  }

  const lblIds = el.getAttribute('aria-labelledby');
  if (lblIds) {
    const text = lblIds
      .split(/\s+/)
      .map((id) => document.getElementById(id))
      .filter((e): e is HTMLElement => e !== null)
      .map((e) => normalizeText(e.innerText || e.textContent || ''))
      .join(' ');
    if (text) return text;
  }

  if (['INPUT', 'SELECT', 'TEXTAREA'].includes(el.tagName)) {
    const fieldset = el.closest('fieldset');
    if (fieldset) {
      const legend = fieldset.querySelector('legend');
      if (legend) return normalizeText((legend as HTMLElement).innerText || legend.textContent || '');
    }
  }

  return '';
}

function getAccessibleName(el: Element): string {
  const ariaLabel = el.getAttribute('aria-label');
  if (ariaLabel) return normalizeText(ariaLabel);

  const labelText = getLabelText(el);
  if (labelText) return labelText;

  const title = el.getAttribute('title');
  if (title) return normalizeText(title);

  const alt = el.getAttribute('alt');
  if (alt) return normalizeText(alt);

  return '';
}

function buildXPath(el: Element): string {
  const parts: string[] = [];
  let node: Element | null = el;

  while (node && node.nodeType === Node.ELEMENT_NODE) {
    const tag = node.tagName.toLowerCase();
    let idx = 1;
    let sibling = node.previousElementSibling;
    while (sibling) {
      if (sibling.tagName.toLowerCase() === tag) idx++;
      sibling = sibling.previousElementSibling;
    }
    parts.unshift(`${tag}[${idx}]`);
    node = node.parentElement;
  }

  return '/' + parts.join('/');
}

function getStableAttributes(el: Element): Record<string, string> {
  const attrs: Record<string, string> = {};
  for (const key of STABLE_ATTRS) {
    const val = el.getAttribute(key);
    if (val && val.trim()) {
      attrs[key] = val.trim();
    }
  }
  return attrs;
}

function buildLocator(el: Element, attrs: Record<string, string>): { primary: string; fallbacks: string[] } {
  const tag = el.tagName.toLowerCase();
  const fallbacks: string[] = [];

  if (attrs['data-testid']) {
    return { primary: `data-testid=${attrs['data-testid']}`, fallbacks };
  }
  if (attrs['data-test']) {
    return { primary: `data-test=${attrs['data-test']}`, fallbacks };
  }
  if (attrs['data-qa']) {
    return { primary: `data-qa=${attrs['data-qa']}`, fallbacks };
  }

  if (attrs.id && !/^\d/.test(attrs.id) && !/\d{5,}/.test(attrs.id)) {
    return { primary: `id=${attrs.id}`, fallbacks };
  }

  if (attrs.name) fallbacks.push(`name=${attrs.name}`);
  if (attrs['aria-label']) fallbacks.push(`aria-label=${attrs['aria-label']}`);
  if (attrs.placeholder) fallbacks.push(`placeholder=${attrs.placeholder}`);
  if (tag === 'a' && attrs.href) fallbacks.push(`href=${attrs.href}`);

  fallbacks.push(`xpath=${buildXPath(el)}`);

  return { primary: fallbacks[0] || tag, fallbacks: fallbacks.slice(1) };
}

function extractNode(el: Element, opts: DistillOptions = {}): DistilledNode | null {
  const tag = el.tagName.toLowerCase();
  const visible = isVisible(el, opts);
  const interactive = isInteractive(el);

  const inputType = (el as HTMLInputElement).type || '';
  const isSpecialInput = tag === 'input' && ['checkbox', 'radio', 'file'].includes(inputType.toLowerCase());

  // Filter hidden elements unless includeHidden is true or it's a special input
  if (!visible && !opts.includeHidden && !isSpecialInput) {
    return null;
  }

  const accessibleName = getAccessibleName(el);
  const visibleText = normalizeText(
    (el as HTMLElement).innerText || el.textContent || '',
    opts.maxTextLength
  );
  const text = accessibleName || visibleText;
  const attrs = getStableAttributes(el);

  const hasValue = interactive || visible || (text && text.length > 0) || Object.keys(attrs).length > 0;

  if (!hasValue) return null;

  const locatorInfo = buildLocator(el, attrs);
  const rect = getRect(el);
  const role = el.getAttribute('role') || tag;

  const editable =
    !(el as HTMLInputElement).disabled &&
    !(el as HTMLInputElement).readOnly &&
    ((tag === 'input' &&
      !['radio', 'checkbox', 'submit', 'button', 'image', 'reset', 'file', 'hidden'].includes(
        inputType.toLowerCase()
      )) ||
      tag === 'textarea' ||
      el.getAttribute('contenteditable') === 'true' ||
      (el.getAttribute('role') || '') === 'textbox');

  return {
    role,
    tag,
    text,
    locator: locatorInfo.primary,
    locatorFallback: locatorInfo.fallbacks,
    interactable: interactive,
    visible,
    editable,
    checked: (el as HTMLInputElement).checked || el.getAttribute('aria-checked') === 'true',
    disabled: (el as HTMLInputElement).disabled || el.getAttribute('aria-disabled') === 'true',
    attributes: attrs,
    rect,
    children: [],
  };
}


const MEANINGFUL_TAGS = new Set([
  'nav', 'main', 'article', 'section', 'aside', 'header', 'footer',
  'form', 'fieldset', 'ul', 'ol', 'table', 'thead', 'tbody', 'tr', 'td', 'th',
  'li', 'label', 'h1', 'h2', 'h3', 'h4', 'h5', 'h6', 'dialog', 'menu',
]);

function isMeaninglessWrapper(node: DistilledNode): boolean {
  if (node.interactable) return false;
  if (node.editable) return false;
  if (node.tag === 'body' || node.tag === 'html') return false;
  if (MEANINGFUL_TAGS.has(node.tag)) return false;
  if (node.text && node.text.trim().length > 0) return false;
  if (node.locator && node.locator.length > 0 && !node.locator.startsWith('xpath=')) return false;
  if (node.role && node.role !== node.tag && node.role !== 'presentation' && node.role !== 'none') return false;
  return true;
}

function flattenNodes(nodes: DistilledNode[]): DistilledNode[] {
  const result: DistilledNode[] = [];
  for (const node of nodes) {
    const flatChildren = flattenNodes(node.children);
    if (isMeaninglessWrapper(node)) {
      result.push(...flatChildren);
    } else {
      node.children = flatChildren;
      result.push(node);
    }
  }
  return result;
}

function pruneEmpty(nodes: DistilledNode[]): DistilledNode[] {
  return nodes.filter((n) => {
    if (n.children.length > 0) {
      n.children = pruneEmpty(n.children);
    }
    return (
      n.interactable ||
      n.editable ||
      (n.text && n.text.trim().length > 0) ||
      n.children.length > 0 ||
      Object.keys(n.attributes).length > 0
    );
  });
}


function distill(options?: DistillOptions): DistilledNode[] {
  const opts: DistillOptions = {
    maxTextLength: 200,
    includeHidden: false,
    checkObscured: false,
    ...options,
  };

  const PRUNE = new Set([
    'SCRIPT', 'STYLE', 'NOSCRIPT', 'SVG', 'TEMPLATE', 'HEAD', 'META', 'LINK',
  ]);

  interface StackItem {
    el: Element;
    node: DistilledNode;
  }

  const stack: StackItem[] = [];
  const roots: DistilledNode[] = [];

  function walk(root: Node) {
    const tw = document.createTreeWalker(root, NodeFilter.SHOW_ELEMENT, {
      acceptNode(n) {
        if (PRUNE.has((n as Element).tagName)) return NodeFilter.FILTER_REJECT;
        return NodeFilter.FILTER_ACCEPT;
      },
    });

    let node: Node | null;
    while ((node = tw.nextNode())) {
      const el = node as Element;
      if (el.shadowRoot) walk(el.shadowRoot);

      const extracted = extractNode(el, opts);
      if (!extracted) continue;

      while (stack.length > 0 && !stack[stack.length - 1].el.contains(el)) {
        stack.pop();
      }

      if (stack.length > 0) {
        stack[stack.length - 1].node.children.push(extracted);
      } else {
        roots.push(extracted);
      }

      stack.push({ el, node: extracted });
    }
  }

  walk(document.body || document.documentElement);

  const flattened = flattenNodes(roots);
  return pruneEmpty(flattened);
}

return distill(options);
}
